# 24.0 image comes with Debian 12 and pep-0668
FROM qwe1/debdocker:24.0

RUN apt-get update && \
    apt-get upgrade --assume-yes && \
    apt-get install --assume-yes --no-install-recommends \
      python3 \
      libc6-dev \
      python3-pip \
      gcc \
      git \
      python3-dev \
      python3-setuptools \
      python3-wheel \
      libssl-dev \
      openssh-client

# https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/
ENV umask=022
ENV PIP_BREAK_SYSTEM_PACKAGES=1

#ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
# https://peps.python.org/pep-0668
# This can be overriden by passing the --break-system-packages option to pip
RUN rm -f /usr/lib/python3.11/EXTERNALLY-MANAGED && \
    pip3 install --upgrade pip

COPY requirements.txt /tmp/
COPY requirements.yml /tmp/

RUN pip3 install -r /tmp/requirements.txt

RUN apt-get purge --autoremove -y \
      libc6-dev \
      gcc \
      libssl-dev \
      python3-dev \
      python3-wheel && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /root/.cache

RUN mkdir -p ~/.ansible/collections && \
    ansible-galaxy collection install -r /tmp/requirements.yml -p ~/.ansible/collections

CMD ["bash"]
